version: '3'

services:
  app:
    build: ./.docker/php
    container_name: oauth-keycloak-app
    volumes:
      - .:/var/www
    networks:
      - nt-keycloak-app

  nginx:
    build: ./.docker/nginx
    container_name: oauth-keycloak-nginx
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    networks:
      - nt-keycloak-app
    depends_on:
      - app

  db:
    build: ./.docker/mysql
    container_name: microservice-videos-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=oauth-keycloak-app
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nt-keycloak-app

  react:
    build: ./.docker/react
    container_name: oauth-keycloak-react
    volumes:
      - .:/home/node/react
    networks:
      - nt-keycloak-app

networks:
  nt-keycloak-app:
    driver: bridge
