version: '3'

services:
  app:
    build: ./.docker/php
    container_name: oauth-keycloak-app
    volumes:
      - .:/var/www
    networks:
      - nt-keycloak-app

  nginx:
    build: ./.docker/nginx
    container_name: oauth-keycloak-nginx
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - nt-keycloak-app
    depends_on:
      - app

  db:
    build: ./.docker/mysql
    container_name: oauth-keycloak-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=oauth-keycloak-app
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nt-keycloak-app

  react:
    build: ./.docker/react
    container_name: oauth-keycloak-react
    ports:
      - 3000:3000
    volumes:
      - ./packages/frontend:/home/node/frontend
    networks:
      - nt-keycloak-app
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: oauth-keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=keycloak
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - nt-keycloak-app

networks:
  nt-keycloak-app:
    driver: bridge
